Navigation for Walk-Throughs
Yubico/developers.yubico.com pull request #345
Opened 2020-12-16 19:34 UTC by FFincannon

2021-01-04 17:24 UTC, elukewalker requested changes
Will merge after commas are added.

2021-01-04 17:24 UTC, elukewalker commented on content/OATH/.conf.json
>  	"SSH_authentication"
@FFincannon, a missing comma is causing the build to fail.

2021-01-04 17:24 UTC, elukewalker commented on content/OTP/.conf.json
>      "OTP_Walk-Through"
@FFincannon, this line of the json object is also missing a comma.

2021-01-04 19:16 UTC, FFincannon commented
@elukewalker , issues resolved per request

2021-02-02 23:21 UTC, FFincannon commented
@elukewalker : Added missing commas and resolved the conflict. This PR is now ready for merging.

2021-02-05 22:21 UTC, elukewalker approved these changes

2021-02-05 22:21 UTC, merged