fix image names
Yubico/developers.yubico.com pull request #571
Opened 2023-12-27 17:00 UTC by spaette

fix typos in bitmap image file names

2024-04-13 15:49 UTC, spaette commented
ping

@csalas-yubico

2024-06-11 17:06 UTC, spaette commented
@emlun 

Can you inform of the status of this PR?

2024-06-11 20:01 UTC, csalas-yubico requested changes
There are breaking changes due to file name changes - see my comments for the issues found

2024-06-11 20:01 UTC, csalas-yubico commented on content/Developer_Program/WebAuthn_Starter_Kit/Installation/Images/mback19-change-execution-role-lambda-function-v1.jpg
Changing this file name caused issues with Figure 19 on page /Developer_Program/WebAuthn_Starter_Kit/Installation/Manual_Back-End_Deployment.html

2024-06-12 18:16 UTC, spaette commented on content/Developer_Program/WebAuthn_Starter_Kit/Back-end_System_Design.adoc
> +image::Images/back1-cognito-user-pool-lambda-triggers-v1.png[]
Is it now loading correctly?

2024-06-15 13:29 UTC, spaette commented
I presume rebasing is unnecessary.

2024-06-20 15:21 UTC, csalas-yubico commented on content/Developer_Program/WebAuthn_Starter_Kit/Back-end_System_Design.adoc
> +image::Images/back1-cognito-user-pool-lambda-triggers-v1.png[]
Confirmed it's loading properly now

2024-06-20 15:27 UTC, csalas-yubico approved these changes
Changes are good - regarding your previous comments, I don't believe a rebase is necessary

2024-06-20 18:47 UTC, merged